version: "3.8"
services:
  json-server:
    container_name: json-server-container
    build:
      context: ./json-server
      dockerfile: Dockerfile
    ports:
      - 9000:9000

  api-gateway:
    container_name: api-gateway-container
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - 2000:2000
    env_file: .env
    depends_on:
      - json-server

  frontend:
    container_name: frontend-container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      - api-gateway
